// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihwpwunlrgovyzvxejzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlod3B3dW5scmdvdnl6dnhlanpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTgzNDksImV4cCI6MjA2NTI5NDM0OX0.c9q192OK6Jbkij-c8k9TuSJkbLnCgyDucyg5oKQqynI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);