// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vikkmczogukpopkudqou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpa2ttY3pvZ3VrcG9wa3VkcW91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjkyNzgsImV4cCI6MjA2NTQwNTI3OH0.TgSewMqdh1e0ivqehjVZfqXRQTQnCwlLCRvMS9njnuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);